// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQqKCOkyoge83t6MsJIutwWKJX-4f7xns',
    appId: '1:59271087159:android:83b114eea4b8e0741eabb2',
    messagingSenderId: '59271087159',
    projectId: 'mentalhealthapp-1ab23',
    storageBucket: 'mentalhealthapp-1ab23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJKI5QPiMi02gY-nG8pMhBjUbvlQi9fKo',
    appId: '1:59271087159:ios:6e526317f4cd970c1eabb2',
    messagingSenderId: '59271087159',
    projectId: 'mentalhealthapp-1ab23',
    storageBucket: 'mentalhealthapp-1ab23.appspot.com',
    androidClientId: '59271087159-30es3b2uvjuj6sqn5kj24rk7idk8en2f.apps.googleusercontent.com',
    iosClientId: '59271087159-elt8nf8aim969kf9bv085kn2avc6j9hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalhealthApp',
  );

}